In [2]:
# ============================================================
# 라이브러리 Import
# ============================================================

# 데이터 처리 및 분석
import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import warnings

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 통계 분석
from scipy import stats
from scipy.stats import shapiro, levene, ttest_ind, chi2_contingency, f_oneway
from scipy.stats import mannwhitneyu, fisher_exact, kruskal
from scipy.stats import skew, kurtosis
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pingouin as pg
import scikit_posthocs as sp

# 머신러닝
from sklearn.preprocessing import MinMaxScaler

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12, 6)

# 참고: seed 고정으로 팀원 간 동일한 결과 재현 가능
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

#모든 컬럼 다 보이게
pd.set_option("display.max_columns", None)
#모든 행도 다 보이게
pd.set_option("display.max_rows", None)


#판다스가 화면에 보여줄 때 잘리지 않게 출력 옵션을 바꾸기
#pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [ ]:
# 1. 파일 위치
metadata_file = "./data/metadata.csv"
data_folder = "./data/data1"
output_folder = "./outputs"

# 2. outputs 폴더 만들기
os.makedirs(output_folder, exist_ok=True)

# 3. metadata 불러오기
metadata = pd.read_csv(metadata_file)

# 4. 컬럼명 공백 제거
metadata.columns = metadata.columns.str.strip()

        type                                         start_time  ambient_temperature battery_id  test_id  uid   filename            Capacity                   Re                  Rct
0  discharge  [2010.       7.      21.      15.       0.    ...                    4      B0047        0    1  00001.csv  1.6743047446975208                  NaN                  NaN
1  impedance  [2010.       7.      21.      16.      53.    ...                   24      B0047        1    2  00002.csv                 NaN  0.05605783343888099  0.20097016584458333
2     charge  [2010.       7.      21.      17.      25.    ...                    4      B0047        2    3  00003.csv                 NaN                  NaN                  NaN
3  impedance                    [2010    7   21   20   31    5]                   24      B0047        3    4  00004.csv                 NaN  0.05319185850921101  0.16473399914864734
4  discharge  [2.0100e+03 7.0000e+00 2.1000e+01 2.1000e+01 2...                    4      B0047        4    5  00005.csv  1.5243662105099023                  NaN                  NaN

In [24]:
metadata.nunique()

type                      3
start_time             2494
ambient_temperature       5
battery_id               34
test_id                 616
uid                    7565
filename               7565
Capacity               2752
Re                     1956
Rct                    1956
dtype: int64

In [4]:
for i in range(1, 10):
    df1 = pd.read_csv(f'data/data1/0000{i}.csv')
    print(i, df1.columns)

1 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')
2 Index(['Sense_current', 'Battery_current', 'Current_ratio', 'Battery_impedance', 'Rectified_Impedance'], dtype='str')
3 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'], dtype='str')
4 Index(['Sense_current', 'Battery_current', 'Current_ratio', 'Battery_impedance', 'Rectified_Impedance'], dtype='str')
5 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')
6 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'], dtype='str')
7 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')
8 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'], dtype='str')
9 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')

1번 5번 세트 /3번 'Voltage_charge' / 2번 4번 세트

- 00001.csv → Discharge(방전) = 첫 번째 방전 기록
- 00002.csv → Impedance(임피던스) = 그 사이 상태 진단
- 00003.csv → Charge(충전) = 다음 충전 기록
- 00004.csv → Impedance(임피던스) = 또 상태 진단
- 00005.csv → Discharge(방전) = 다음 방전 기록

데이터는 한 줄 한 줄이 “일반 거래 데이터”가 아니라, 배터리의 충전/방전/임피던스 측정 사이클을 의미합니다.
=> 리튬이온 배터리를 여러 번 충전·방전·임피던스 측정한 실험 기록

Charge → Discharge = 1 cycle

- type	실험 유형 (charge, discharge, impedance)
- start_time	테스트 시작 시간
- ambient_temperature	실험 환경의 온도(°C)
- battery_id	배터리 식별 ID
- test_id	실험 ID
- uid	실험 샘플 ID
- filename	데이터 파일명
- Capacity	배터리 현재 용량(Ah)
- Re	전해질 저항(Ω)
- Rct	충전 전달 저항(Ω)
- Voltage_measured	배터리 측정 전압(V)
- Current_measured	배터리 측정 전류(A)
- Temperature_measured	배터리 실시간 온도(°C)
- Current_load	배터리 부하 전류(A)
- Voltage_load	배터리 부하 전압(V)

RUL 칼럼 값이 없어요!

**NASA 배터리 데이터에서 RUL 칼럼 추가하기(feature engineering)**

그렇다면 RUL이란?
RUL은 **현재 타임스텝(t)에서 배터리의 마지막 수명(EOL)까지 남은 사이클 수**

                                           RUL=EOL−t

도메인 지식이 꼭 필요해요!

✔**Step 1:** 배터리별 **초기 용량**을 확인하고**80% 기준** 설정

✔**Step 2:** 배터리별 **EOL (마지막 유효 사이클)** 찾기

✔**Step 3: RUL = EOL - 현재 Cycle** 계산

✔**Step 4:** 데이터셋에 **RUL 칼럼 추가**

In [5]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   type                 7565 non-null   str
 1   start_time           7565 non-null   str
 2   ambient_temperature  7565 non-null   int64
 3   battery_id           7565 non-null   str
 4   test_id              7565 non-null   int64
 5   uid                  7565 non-null   int64
 6   filename             7565 non-null   str
 7   Capacity             2794 non-null   str
 8   Re                   1956 non-null   str
 9   Rct                  1956 non-null   str
dtypes: int64(3), str(7)
memory usage: 1.3 MB

In [ ]:
metadata['battery_id'].nunique()

34

In [10]:
metadata['battery_id'].value_counts()

battery_id
B0006    616
B0005    616
B0007    616
B0034    486
B0033    486
B0036    486
B0018    319
B0043    275
B0042    275
B0044    275
B0054    253
B0056    252
B0055    252
B0047    184
B0045    184
B0048    184
B0046    184
B0041    163
B0053    137
B0039    122
B0040    122
B0038    122
B0032     97
B0029     97
B0030     97
B0031     97
B0028     80
B0027     80
B0025     80
B0026     80
B0049     62
B0050     62
B0052     62
B0051     62
Name: count, dtype: int64

In [ ]:
summary = pd.DataFrame({
    "dtype": metadata.dtypes,
    "non_null": metadata.count(),
    "null": metadata.isnull().sum()
})

summary

                     dtype  non_null  null
type                   str      7565     0
start_time             str      7565     0
ambient_temperature  int64      7565     0
battery_id             str      7565     0
test_id              int64      7565     0
uid                  int64      7565     0
filename               str      7565     0
Capacity               str      2794  4771
Re                     str      1956  5609
Rct                    str      1956  5609

- **Charge(충전)**: 배터리에 에너지를 저장하는 과정
- **Discharge(방전)**: 배터리에 저장된 에너지를 사용하는 과정
- **Impedance(내부 저항 측정)**: 배터리 내부 저항 특성을 측정하는 과정
- **Capacity(용량)**: 배터리가 저장하고 방전할 수 있는 전하량
- **RUL(Remaining Useful Life)**: 현재 시점에서 앞으로 남은 사용 가능 수명


**🔋 고려해야할 분석 요소**

- **배터리 성능 지표** → `Capacity`, `Voltage_measured`, `Temperature_measured` 변화 분석
- **충·방전 사이클** → `Cycle` 별 용량 감소 추이 확인
- **온도 영향 분석** → `ambient_temperature`가 배터리 성능에 미치는 영향
- **배터리 저항 증가 여부** → `Re`, `Rct` 값이 포함된 경우 추가 분석

In [19]:
metadata['Capacity'].value_counts().sort_values(ascending=False)

Capacity
[]                      25
0                       19
1.6743047446975208       1
1.5243662105099023       1
1.5080762969973425       1
1.4835577960067696       1
1.4671391666146525       1
1.448858156982267        1
1.4458534180949325       1
1.431118266178283        1
1.4192745516578533       1
1.3999974221808271       1
1.3885156686114437       1
1.3652234669528964       1
1.4060442272970963       1
1.4057541613525781       1
1.3867662881727878       1
1.3705053061420223       1
1.3497431114823601       1
1.3251533367939783       1
1.3111943869635805       1
1.3394234405932892       1
1.2849157142560723       1
1.281719159327807        1
1.2600051642942829       1
1.266070385993126        1
1.2413590294280803       1
1.2298873703485311       1
1.228088614506696        1
1.2139857189070042       1
1.2173435064564189       1
1.2073445944515917       1
1.18804049227045         1
1.186304749886542        1
1.2613935471028506       1
1.2648246158850653       1
1.2466494548982199       1
1.2333924152795082       1
1.2129250072037692       1
1.1999106597943647       1
1.1902559038393383       1
1.1892563795455853       1
1.167069685125939        1
1.1615348403090369       1
1.1555563844349988       1
1.1488524666097713       1
1.143572986788779        1
1.1418015379428537       1
1.136058647502255        1
1.1236364680969286       1
1.1320498900328944       1
1.1170101762158153       1
1.120043039721982        1
1.1059773445917063       1
1.1907902374762016       1
1.2012387088454022       1
1.1906909549024802       1
1.1764375730308343       1
1.1628110372792353       1
1.1516152840582585       1
1.1583673498348623       1
1.1692285288386206       1
1.1588148476218465       1
1.1439588147705457       1
1.1383941068159398       1
1.2213102850395667       1
1.2031062978889062       1
1.1897147112197684       1
1.177422568842014        1
1.158443027293818        1
1.1567087516841796       1
1.0819793880779518       1
0.927952404748273        1
0.885193608411576        1
0.8581010699478283       1
0.8409352213456689       1
0.8245471942901911       1
0.7935960418803983       1
0.8183676087159205       1
0.7977644276409412       1
0.7993777411831636       1
0.7783107440628891       1
0.7803738231239117       1
0.7713058245640294       1
0.795279016979026        1
0.7824128169919247       1
0.7649414992231182       1
0.7544899426779375       1
0.7504048978314295       1
0.7407258109620256       1
0.7308525593793626       1
0.7287255851177903       1
0.7161023377036263       1
0.7129204834988017       1
0.7141991829499618       1
0.7190570819844222       1
0.7173975428775917       1
0.7071027496463946       1
0.703531206505542        1
0.6941108278958862       1
0.6914114388869608       1
0.6971551798505504       1
0.6832460217432723       1
0.6822029317493292       1
0.7289529213213379       1
0.7139321758287004       1
0.6957731747455482       1
0.7018312962317095       1
0.6911808244378487       1
0.6843279752855028       1
0.6741394908812485       1
0.6670070174301739       1
0.6804085117374855       1
0.6617864063235485       1
0.6623168733492338       1
0.6679358357181778       1
0.6488990885270688       1
0.6503639129625527       1
0.6572077690202801       1
0.6363517458476216       1
0.6536449360948587       1
0.6391428272150887       1
0.6482206049496236       1
0.6287957471922729       1
0.6380571850193401       1
0.6554825047832906       1
0.6484934835397033       1
0.6454071687844921       1
0.6427008031845645       1
0.6352454880802477       1
0.6156760019587869       1
0.6170833682807023       1
0.6434227390858672       1
0.6278124433742752       1
0.6290078315253372       1
0.6266355568292261       1
0.6495813516716594       1
0.6337485177966306       1
0.6298550929085645       1
0.6183063778386736       1
0.6069476168507777       1
1.6579955793677608       1
1.5076933476098775       1
1.4989223343608031       1
1.4782919502497789       1
1.461856891390611        1
1.4509592706473475       1
1.451746997147108        1
1.444392866287476        1
1.432738323965376        1
1.417241201438662        1
1.4057559944573452       1
1.3902706269897063       1
1.4196659307880326       1
1.4190563985232272       1
1.404272356704056        1
1.3916140490958342       1
1.3749618350294734       1
1.3545155713071164       1
1.3440223073315984       1
1.372384475860572        1
1.3184105752674413       1
1.3112727599578604       1
1.2970172419001187       1
1.2995219526631718       1
1.2826154066729571       1
1.2752890152407          1
1.2735572473264072       1
1.2594114333938535       1
1.2631632585495876       1
1.2491717310136363       1
1.233984347835307        1
1.240031992028868        1
1.30370857198071         1
1.315055963470538        1
1.2888738300982074       1
1.2877137595885193       1
1.2673379985315463       1
1.250594345697306        1
1.2487131179395878       1
1.248002326082933        1
1.2300895244599586       1
1.2244197121500935       1
1.2186682845116386       1
1.2037865236033616       1
1.1947642300832226       1
1.2052091893871497       1
1.1955746593628465       1
1.1888497102149884       1
1.1915605250807406       1
1.1726587153109655       1
1.1841133872494156       1
1.1576825122317769       1
1.259355851168598        1
1.265883375278026        1
1.2472598673184119       1
1.232808747256218        1
1.2319592783041904       1
1.220785786262778        1
1.2275441303266783       1
1.2386788414290355       1
1.2283577755407058       1
1.2095481507570451       1
1.2082142070681048       1
1.2998734542832147       1
1.2691220651743778       1
1.2555144634690785       1
1.2519876926897657       1
1.2374982003019996       1
1.2231273969878986       1
1.7282392323598248       1
1.5161488467923143       1
1.503121190703977        1
1.48586566102824         1
1.4694562316392716       1
1.4589554592644807       1
1.4556853555098295       1
1.456232262380321        1
1.4440592236675138       1
1.428294264765868        1
1.4199848948034668       1
1.4043226018516568       1
1.4234351301615986       1
1.4339948857967295       1
1.4185177047756572       1
1.4056313337829422       1
1.3890214025155618       1
1.3723339082737365       1
1.3615778905990565       1
1.4100282016237429       1
1.3395671374926488       1
1.3291515487117478       1
1.3181687033905718       1
1.312423708466101        1
1.2993237532162487       1
1.2877483042174591       1
1.2865282739749122       1
1.2719636386987183       1
1.2714495345417192       1
1.2615423884659074       1
1.2421201619204132       1
1.2402537441669796       1
1.2851130012242886       1
1.3043327841699193       1
1.2778639041619957       1
1.2723464591651539       1
1.2477883952768762       1
1.2352499196655526       1
1.229251291851949        1
1.223890910501634        1
1.205423323571373        1
1.1957824090008151       1
1.1900729496698461       1
1.179201763233652        1
1.169504032514554        1
1.16772376849918         1
1.1579256145829042       1
1.1499812813376982       1
1.150285902223034        1
1.1349452274085248       1
1.1380960963513609       1
1.123711172150547        1
1.214119211354098        1
1.211944797522819        1
1.1971248679331923       1
1.1822892151870987       1
1.1645336676778397       1
1.1535559567518647       1
1.1601987101282065       1
1.1711716308206082       1
1.1563410270783216       1
1.141082456193516        1
1.1352383596118123       1
1.2530847858282803       1
1.2050453590356518       1
1.19119860196273         1
1.17463817374538         1
1.1555432048235512       1
1.1538041170229467       1
1.713782642126885        1
1.6955681658647108       1
1.6814906372051954       1
1.6786372409532953       1
1.6694168550864992       1
1.6611938521224778       1
1.6506423382064332       1
1.6424273190907783       1
1.6353664801041328       1
1.633232875930849        1
1.6258840554387932       1
1.617976174654771        1
1.6136652707273988       1
1.605821026619692        1
1.6033527961961531       1
1.5951342406182645       1
1.5878135544728507       1
1.5800601969084245       1
1.575565087879128        1
1.5950169012164208       1
1.5898075522577595       1
1.5807953202097411       1
1.5704333289187615       1
1.5643368431897877       1
1.558307017802491        1
1.5537149289772467       1
1.549528250585513        1
1.5424430535161062       1
1.54256227031715         1
1.5309356452520158       1
1.5247733176952427       1
1.5196742408779502       1
1.5123696925788683       1
1.499914486202397        1
1.4924106271188253       1
1.492624987952706        1
1.4924024018806028       1
1.4853020201751674       1
1.477208127101587        1
1.4694738525181406       1
0.057034391042653794     1
0.0571536334895882       1
0.05729366005937665      1
0.05744203185278054      1
0.06713062107721124      1
0.06714781920234739      1
0.06732001211690299      1
0.06784038051613318      1
0.06799604927210635      1
0.06828011147886554      1
0.06844632943125976      1
0.06851361914788083      1
0.06887402435616684      1
0.056544389321695726     1
0.06918353164189846      1
0.059122086455436665     1
0.06956120084140223      1
0.07017897804376615      1
0.07028148183862523      1
0.05787364202878375      1
0.07056618554293374      1
0.057989410208958        1
0.07129266446800787      1
0.07146546557664281      1
0.0716254973792324       1
0.07192596356272017      1
0.058840095111364746     1
0.07213853480103966      1
0.07231835711877917      1
0.05938170626668099      1
0.07294488485625279      1
0.07306917734079586      1
0.07317054128128272      1
0.07347430293304898      1
0.06010697591831878      1
0.07383162509955737      1
0.060495215307428206     1
0.060604010237618126     1
0.06073438432235217      1
0.06099653048237791      1
0.061130459259873135     1
0.06129124410987595      1
0.06130329065804092      1
0.061151661574090986     1
0.061405387192057306     1
0.06175780765942851      1
1.5250840516518187       1
1.552568811301301        1
1.5427752626774387       1
1.5331932831264679       1
1.5152721949172019       1
1.5074989761997712       1
1.4896288908647644       1
1.4780778852088083       1
1.4700035345334466       1
1.4565623180137077       1
1.445976962830235        1
1.4325855992469252       1
1.4197344854662965       1
1.401262575071573        1
1.3862945308535968       1
1.384130256052478        1
1.3651743201871416       1
1.361508332192898        1
1.351001663879717        1
1.3282588067265129       1
1.3257206687421472       1
1.3142909715978441       1
1.3003260094811093       1
1.2881071401556836       1
1.2767801501201566       1
1.7048641073512139       1
1.8940319526948572       1
1.8747686491853095       1
1.8654947184112376       1
1.8527398169018068       1
1.844174397003866        1
1.8430238477512753       1
1.8302818174911863       1
1.8173838456081814       1
1.8057992981104682       1
1.8149829605049186       1
1.7995150369321797       1
1.7866516942518147       1
1.7735550719416031       1
1.769995333364443        1
1.799526080374287        1
1.7968530684449833       1
1.7838265504081745       1
1.7696444491040102       1
1.7512940457049684       1
1.7697554297961993       1
1.7547726933914918       1
1.7389166355812984       1
1.7337200518764075       1
1.7150972597500092       1
1.7462926148815636       1
1.719149261914565        1
1.711582246191498        1
1.6951051195225901       1
1.7005124371100973       1
1.7080989351250158       1
1.691435430587127        1
1.6844494328889932       1
1.664037581688075        1
1.6686372014231974       1
1.6899344075625968       1
1.669431712846442        1
1.6634226761839213       1
1.6436152195947373       1
1.6358000873538245       1
0.11903831859341765      1
0.4729861500927512       1
0.16280793829202067      1
0.4787632853388766       1
0.4711383364607152       1
0.4668172561120673       1
0.4699932676625547       1
0.4627052684317185       1
0.46049447826560974      1
0.4412227248835694       1
0.44354421943965844      1
0.4126655541164234       1
1.7461791006389626       1
1.7695250734505363       1
1.7715391419501945       1
1.770625483958279        1
1.7704040639447296       1
1.7695081788801759       1
1.7638356274269416       1
1.7715725869786123       1
1.7701196454489683       1
1.7667569752860521       1
1.7648743629092642       1
1.763838685943225        1
1.7657225752056789       1
1.7645632809383045       1
1.7608991948479125       1
1.7598362095817717       1
1.7590955400143164       1
1.7560495443976523       1
1.7571677199949287       1
1.7558911269459976       1
1.7533419072229914       1
1.7506673845335168       1
1.7510006664162403       1
1.7496058853847873       1
1.7477359172183355       1
1.7444225468099093       1
1.743308366083936        1
1.6556691733888471       1
1.64297669457593         1
1.6343822729361266       1
1.6265067062165601       1
1.618865991735961        1
1.6114968339209264       1
1.3240805773461226       1
1.3153386221697692       1
0.6734628137095633       1
0.7913062105760345       1
0.7865824034601745       1
0.7795871426061582       1
0.7628241523125163       1
0.7405021514606399       1
0.7783970881100656       1
0.7733165409025605       1
0.7589575236409498       1
0.7407399462256391       1
0.7446218752617147       1
0.7149875629820736       1
1.7075144448533202       1
1.730880859428193        1
1.7328212845233328       1
1.7317734323431513       1
1.7341296392350067       1
1.7334756929990074       1
1.7243057179457875       1
1.7318975861687205       1
1.7333691208377457       1
1.732175650153278        1
1.7334832776102866       1
1.732372495746513        1
1.7338175297202416       1
1.7329630786357868       1
1.7318839084573339       1
1.7306960059812662       1
1.7296011601947467       1
1.7296187381064656       1
1.7307198617163877       1
1.729274556175907        1
1.7297962212599596       1
1.7268942069037494       1
1.7272191689306016       1
1.7285674981160106       1
1.726636381605547        1
1.7262424141835067       1
1.7252725927602899       1
1.6668026877455053       1
1.666754853762041        1
1.6583274448761054       1
1.65032263550715         1
1.6493406341242296       1
1.641919055037739        1
0.425812451177779        1
0.5569902643736575       1
1.697507332205763        1
1.844701206961174        1
1.8254376674722927       1
1.815750429913437        1
1.8132993337127028       1
1.8151647619660576       1
1.8143317955190057       1
1.801343601809866        1
1.7881558802945825       1
1.7760714604539518       1
1.7852807447597443       1
1.7698116401111978       1
1.7565231680521758       1
1.7543413277348154       1
1.7392875506998715       1
1.7797845109331345       1
1.7657088508465202       1
1.7523941408724169       1
1.7380191225603105       1
1.7312214443143976       1
1.7379128985265808       1
1.7224270683625882       1
1.7184213765608034       1
1.7010220930648232       1
1.693698739563104        1
1.713072721286705        1
1.6976972688567131       1
1.6899314034061208       1
1.685023551367069        1
1.678389965463405        1
1.6737947494868326       1
1.6687898927884715       1
1.6492566306631427       1
1.6409676757039668       1
1.6456360229757092       1
1.654547743574037        1
1.6461201520877546       1
1.6275119188151763       1
1.6200530533464497       1
1.612079811711934        1
1.8046847720100736       1
1.8047833214525881       1
1.797618668222458        1
1.7929913687761174       1
1.7919180081592216       1
1.775026135903797        1
1.7920487852223415       1
1.790475801581265        1
1.7868365091987264       1
1.7871529619962185       1
1.7816340617009505       1
1.7850235136604733       1
1.7803865429693038       1
1.7789060856417256       1
1.7738387518973049       1
1.769682881523146        1
1.7408787283206992       1
1.7648189744011906       1
1.7617857390844023       1
1.75770610357021         1
1.7519375960601256       1
1.7521244035832177       1
1.7597714133989641       1
1.7483011320324189       1
1.7411482627836237       1
1.7363833316311177       1
1.736559066269527        1
1.7172335652295245       1
1.7287126633755356       1
1.7314706281853145       1
1.7282350363146088       1
1.720344742291621        1
1.7221734367707637       1
1.708669577331945        1
1.7036476485918646       1
1.6958375743577971       1
1.6949064846676911       1
1.6874768094352455       1
1.685989172917945        1
1.6782864747774933       1
1.6739647640901527       1
1.6722378801237066       1
1.6759897900491967       1
1.6618247672847988       1
1.6606710352566112       1
1.6530644874507203       1
1.649953986270456        1
1.681297805444492        1
1.6700520424481298       1
1.667181860354792        1
1.6568865613275168       1
1.6449819446579936       1
1.639214585000014        1
1.6410599890208055       1
1.6432696512198481       1
1.6298673102402295       1
1.6238536344658807       1
1.6186308887044174       1
1.6193418112441196       1
1.614593271326993        1
1.6072040891927848       1
1.6012663590062357       1
1.5940407410631041       1
1.5946888289374477       1
1.5882100957302596       1
1.587985558077698        1
1.5799165406650344       1
1.5655946193652834       1
0.07070127737340176      1
0.08416878530139071      1
0.08443785621465827      1
0.08478919060590338      1
0.09334258183442584      1
0.10603180131397782      1
0.106505866207118        1
0.09439111585512952      1
0.09450595927387112      1
0.08211456108215626      1
0.09518470631946747      1
0.09539129998659052      1
0.08289664565854568      1
0.08343199036452603      1
0.09624772156495698      1
0.0871279249656989       1
0.09681912182757578      1
0.08440054891345107      1
0.09770121716674529      1
0.08517426476572666      1
0.08471993544879124      1
0.08548836969893649      1
0.08577749933433501      1
0.08595553255245832      1
0.08614796979658328      1
0.08652450808993331      1
0.08676036428685732      1
0.08662025389371077      1
0.0869802394927499       1
0.07387787113473963      1
0.08775865702231889      1
0.08790576300272998      1
0.08808784882200178      1
0.08834250268158712      1
0.07463055332745072      1
0.07485698665122698      1
0.07527573643141765      1
0.07532351860488727      1
0.07553765302367196      1
0.07584285606128259      1
0.0759921803489148       1
0.07621652609591999      1
0.06216923141552526      1
0.0759822277461493       1
0.06227013548943564      1
0.06259446608798445      1
1.4377344766079456       1
1.5246019289244055       1
1.5215273965539478       1
1.5155323631175952       1
1.5044249661534554       1
1.5001507149498807       1
1.489011227320312        1
1.4810149357562845       1
1.476262027748574        1
1.4662551025438961       1
1.4593282593817019       1
1.445704157754381        1
1.4400686089389023       1
1.4290313659547842       1
1.414172188151386        1
1.415603079129078        1
1.3994410223300702       1
1.3959635285794907       1
1.3929784652630588       1
1.3740772023800918       1
1.3752493030002435       1
1.3671966130854505       1
1.356887600783644        1
1.3449320225969348       1
1.3374691704584258       1
0.7459302957645664       1
1.6623217152845853       1
1.645087369694532        1
1.620729289277574        1
1.5967402025126005       1
1.4856500618812698       1
1.4866702197497013       1
1.4701330958405268       1
1.4565041801019636       1
1.4418961035576472       1
1.4370949588970292       1
1.4458703624967404       1
1.4321040545618373       1
1.426720633302465        1
1.4230846885129826       1
1.4409479522418907       1
1.486901544051865        1
1.5245313226850703       1
1.4629049605190707       1
1.4230794508549893       1
1.4051040863603435       1
1.6329463925070862       1
1.5687138208259117       1
1.5149520966053402       1
1.4855182940634626       1
1.480771929049074        1
1.484026357317059        1
1.4922153055506522       1
1.473312924099279        1
1.441593178980006        1
1.4225873198015788       1
1.4266489379486664       1
1.4596775560238577       1
1.4396159938545154       1
1.4195512657848512       1
1.4118101714470452       1
1.4044196701845313       1

In [23]:
metadata["Capacity"].apply(type).value_counts()

Capacity
<class 'float'>    4771
<class 'str'>      2794
Name: count, dtype: int64

In [ ]:
import pandas as pd

all_data = []

for i in range(len(metadata)):
    file_name = metadata.loc[i, "filename"]
    file_path = "data/data1/" + file_name
    
    df = pd.read_csv(file_path)
    
    df["filename"] = file_name
    df["type"] = metadata.loc[i, "type"]
    df["battery_id"] = metadata.loc[i, "battery_id"]
    df["start_time"] = metadata.loc[i, "start_time"]
    
    all_data.append(df)

full_data = pd.concat(all_data, ignore_index=True)

In [25]:
df = metadata.copy()

In [27]:
def clear_time(x):
    # 사용할 리스트
    nums = []

    # 임시 저장용
    current = ''

    # 반복문으로 숫자만 뽑아내기
    for ch in x:
        # 숫자형이거나 형태 다른 숫자 뽑아내기
        if ch.isdigit() or ch in ['.', '_', 'e', 'E', '+']:
            current += ch
        else:
            if current != '':
                nums.append(current)
                current = ''

    # 숫자 남아있을 수도 있으니 한번 더 리스트에 append
    if current != '':
        nums.append(current)

    # 연월일시분초 하면 최소 6자리, 그 이하는 버림
    if len(nums) < 6:
        return None

    # num 리스트 숫자형으로 변환, 연월일시분초이므로 앞에 6개만 숫자 변환
    try:
        nums = list(map(float, nums[:6]))
    except:
        return None

    # 각 숫자에 의미 부여
    year, month, day, hour, minute, second = nums

    # 이상치 제거
    if not (
        2000 < year
        and 1 <= month <= 12
        and 1 <= day <= 31
        and 0 <= hour < 24
        and 0 <= minute < 60
        and 0 <= second < 60
    ):
        return None

    # Timestamp로 date_time 변환
    return pd.Timestamp(
        int(year), int(month), int(day),
        int(hour), int(minute), int(second)
    )


df['start_time'] = df['start_time'].apply(clear_time)
df = df.dropna(subset=['start_time'])