In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math
import platform

In [2]:
df = pd.read_csv("metadata.csv")
test_df = df.copy()

In [14]:
# 크기 확인
df.shape

(7565, 10)

In [21]:
# 컬럼 확인
test_df.columns

Index(['type', 'start_time', 'ambient_temperature', 'battery_id', 'test_id',
       'uid', 'filename', 'Capacity', 'Re', 'Rct'],
      dtype='str')

In [15]:
# 전반적인 구조와 결측치 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   type                 7565 non-null   str
 1   start_time           7565 non-null   str
 2   ambient_temperature  7565 non-null   int64
 3   battery_id           7565 non-null   str
 4   test_id              7565 non-null   int64
 5   uid                  7565 non-null   int64
 6   filename             7565 non-null   str
 7   Capacity             2794 non-null   str
 8   Re                   1956 non-null   str
 9   Rct                  1956 non-null   str
dtypes: int64(3), str(7)
memory usage: 591.1 KB

In [24]:
# 컬럼당 고유값 개수
test_df.nunique()

type                      3
start_time             2494
ambient_temperature       5
battery_id               34
test_id                 616
uid                    7565
filename               7565
Capacity               2752
Re                     1956
Rct                    1956
dtype: int64

In [17]:
# 수치 데이터 요약
df.describe()

       ambient_temperature      test_id          uid
count          7565.000000  7565.000000  7565.000000
mean             20.017713   176.012558  3783.000000
std              11.082914   152.174147  2183.971726
min               4.000000     0.000000     1.000000
25%               4.000000    55.000000  1892.000000
50%              24.000000   129.000000  3783.000000
75%              24.000000   255.000000  5674.000000
max              44.000000   615.000000  7565.000000

In [23]:
# 결측치 개수 상세 확인
df.isnull().sum()

type                      0
start_time                0
ambient_temperature       0
battery_id                0
test_id                   0
uid                       0
filename                  0
Capacity               4771
Re                     5609
Rct                    5609
dtype: int64

In [22]:
# 중복 데이터 확인
df.duplicated().sum()

np.int64(0)

In [8]:
test_df.head()

,type,start_time,ambient_temperature,battery_id,test_id,uid,filename,Capacity,Re,Rct
0,discharge,[2010. 7. 21. 15. 0. ...,4,B0047,0,1,00001.csv,1.6743047446975208,NaN,NaN
1,impedance,[2010. 7. 21. 16. 53. ...,24,B0047,1,2,00002.csv,NaN,0.05605783343888099,0.20097016584458333
2,charge,[2010. 7. 21. 17. 25. ...,4,B0047,2,3,00003.csv,NaN,NaN,NaN
3,impedance,[2010 7 21 20 31 5],24,B0047,3,4,00004.csv,NaN,0.05319185850921101,0.16473399914864734
4,discharge,[2.0100e+03 7.0000e+00 2.1000e+01 2.1000e+01 2...,4,B0047,4,5,00005.csv,1.5243662105099023,NaN,NaN

In [9]:
test_df.tail()

,type,start_time,ambient_temperature,battery_id,test_id,uid,filename,Capacity,Re,Rct
7560,impedance,[2010. 9. 30. 7. 36. ...,24,B0055,247,7561,07561.csv,NaN,0.0968087979207628,0.15489738203707232
7561,discharge,[2010. 9. 30. 8. 8. ...,4,B0055,248,7562,07562.csv,1.0201379996149256,NaN,NaN
7562,charge,[2010. 9. 30. 8. 48. 54.25],4,B0055,249,7563,07563.csv,NaN,NaN,NaN
7563,discharge,[2010. 9. 30. 11. 50. ...,4,B0055,250,7564,07564.csv,0.9907591663373165,NaN,NaN
7564,charge,[2010. 9. 30. 12. 31. ...,4,B0055,251,7565,07565.csv,NaN,NaN,NaN